### ISSUE TITLE
xmlschema installed to wrong location

### ISSUE THREAD

**Issue by GarethDJohn** [conda-forge/xmlschema-feedstock#2]
When using miniconda3-4.2.12 (python 3.5) and installing xmlschema from conda-forge, the package gets installed to a 'site-packages' directory directly under the env root:

```
$ wget https://repo.continuum.io/miniconda/Miniconda3-4.2.12-MacOSX-x86_64.sh
$ bash Miniconda3-4.2.12-MacOSX-x86_64.sh -b -p miniconda/4.2.12
$ PATH=miniconda/4.2.12/bin:$PATH conda install -c conda-forge xmlschema
$ find miniconda/4.2.12 -type d -name xmlschema
miniconda/4.2.12/**site-packages/xmlschema**
miniconda/4.2.12/pkgs/xmlschema-0.9.18-py_0/site-packages/xmlschema
$ PATH=miniconda/4.2.12/bin:$PATH python -c "import xmlschema"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'xmlschema'
```

This site-packages directory is not in the python path. Trying this with Miniconda3-4.3.11 (python 3.6) shows that xmlschema is correctly installed to the lib/python3.6/site-packages directory:

```
$ wget https://repo.continuum.io/miniconda/Miniconda3-4.3.11-MacOSX-x86_64.sh
$ bash Miniconda3-4.3.11-MacOSX-x86_64.sh -b -p miniconda/4.3.11
$ PATH=miniconda/4.3.11/bin:$PATH conda install -c conda-forge xmlschema
$ find miniconda/4.3.11 -type d -name xmlschema
miniconda/4.3.11/**lib/python3.6/site-packages/xmlschema**
miniconda/4.3.11/pkgs/xmlschema-0.9.18-py_0/site-packages/xmlschema
$ PATH=miniconda/4.3.11/bin:$PATH python -c "import xmlschema"
<no errors emitted>
```

I raised this issue on the main conda repo but I was pointed in this direction as it was suggested it was a packaging issue.

**Comment by ccwang002** [comment]
Would you mind pointing me to the issue you reported?

**Comment by ccwang002** [comment]
The installation worked for me on Python 3.5 using the lastest conda 4.3.29:

```bash
conda create -y -n py35 python=3.5 xmlschema 
source activate py35
find ~/miniconda3/envs/py35 -type d | grep xmlschema
~/miniconda3/envs/py35/lib/python3.5/site-packages/xmlschema
```

I will try the older conda version but let me know if this issue can be fixed by updating the conda itself.

**Comment by isuruf** [comment]
You need conda>=4.3. Update conda, remove xmlschema and install again

**Comment by ccwang002** [comment]
I just did what @isuruf said and it worked on conda 4.2.12.

```bash
conda uninstall xmlschema
conda update conda  # conda should have run this itself already
conda install xmlschema
```

**Comment by GarethDJohn** [comment]
Hi, thanks for the replies. We are unfortunately restricted to (mini)conda 4.2.12 at the moment. I know that as a workaround I can just modify PYTHONPATH to include $env/site-packages but was wondering if there was another solution.

**Comment by isuruf** [comment]
You can install miniconda3-4.2.12 and update the conda there. If that's also not possible, you'll have to use pip to install xmlschema.

**Comment by GarethDJohn** [comment]
Ok thanks - do you have any more info on what causes this issue?

**Comment by isuruf** [comment]
`xmlschema` is a `noarch: python` package which requires conda>=4.3. See https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#architecture-independent-packages

**Comment by GarethDJohn** [comment]
Ah understood - thank you for your time and explanation.
